# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel

sudo: false
cache: packages

r_binary_packages:
  - stringr
  - dplyr
  - igraph
  - RCurl
  - XML
  - git2r

warnings_are_errors: false

env:
  - R_REMOTES_UPGRADE="always"

before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j4' > ~/.R/Makevars
  - echo 'options(Ncpus = 4)' > ~/.Rprofile
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install(dependencies=TRUE)'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"


before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
